# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install puppeteer --save-dev
    npm install
  displayName: 'npm install dependencies and build'
  
- script: |
    npm update
  displayName: 'Update modules'

- script: ng test --watch=false --code-coverage
  displayName: 'Run ng test'


